;;;; cl-workbench-template: dev-swank-server.lisp.template template=965ec2252004 rendered=40cecc365d2f version=0.13.0-dev
;;;; Persistent Swank development image for web3-lisp.
;;;;
;;;; Runs INSIDE the project container (started by scripts/dev.sh via
;;;; docker run): the image's .sbclrc already loads /opt/quicklisp. Swank is
;;;; not baked into the image, so the first start of each container
;;;; quickloads it. Listens on 0.0.0.0 in-container — the container's
;;;; loopback is unreachable from the host — and dev.sh never publishes the
;;;; port: every eval is a `docker exec` of the Workbench client.
;;;; Generated by `cl-workbench init`; regenerate with `cl-workbench init --update`.

(defun getenv/default (name default)
  (or (sb-ext:posix-getenv name) default))

(let ((port (parse-integer (getenv/default "DEV_SWANK_PORT" "4007"))))
  (funcall (find-symbol "QUICKLOAD" "QL") "swank" :silent t)
  (format t "~&;;; Loading web3-lisp systems (a cold FASL volume compiles everything first)~%")
  (asdf:load-system "web3/tests")
  (format t "~&;;; Starting Swank on 0.0.0.0:~D (in-container)~%" port)
  (funcall (find-symbol "CREATE-SERVER" "SWANK")
           :interface "0.0.0.0" :port port :dont-close t)
  (format t "~&;;; web3-lisp Swank dev image ready.~%")
  (loop (sleep 3600)))
