#!/usr/bin/env bash
# cl-workbench-template: dev.sh.template template=eecd1131b3a5 rendered=593324d40ad6 version=0.13.0-dev
# dev.sh — warm-image development helper for web3-lisp (Common Lisp
# Workbench managed). Generated by `cl-workbench init`; regenerate a stale copy
# with `cl-workbench init --update`. Project-specific knobs are the variables
# right below; everything else is the generic lifecycle every managed project
# shares.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${DEV_SWANK_PORT:-4007}"   # Swank port INSIDE the container; never published
DOCKER=docker
IMAGE="web3-lisp-sbcl:2.5.2-1"                 # pinned project image (docker/Dockerfile)
PROJECT_ID="web3-lisp"       # value of PROJECT_LABEL on everything we own
HEAP=4096                     # --dynamic-space-size for the warm image
REQUIRED_PATHS=()
DOCS_CONFIGURED=0

# The Lisp form that runs the whole suite. It must signal an error (so the eval
# exits non-zero) when anything fails or nothing was selected, and print one
# `cl-workbench-checks: N` line for the counted gate.
TEST_ALL_FORM=$(cat <<'CL_WORKBENCH_FORM'
(multiple-value-bind (passed failed) (web3-tests/runner:run-all-tests) (format t "~&cl-workbench-checks: ~D~%" (+ passed failed)) (when (zerop (+ passed failed)) (error "no web3 tests ran")) (unless (zerop failed) (error "~D web3 test(s) failed" failed)))
CL_WORKBENCH_FORM
)
# Optional: the form for one selector; `{selector}` is replaced by the argument.
TEST_ONE_FORM=$(cat <<'CL_WORKBENCH_FORM'
(let ((web3-tests/runner::*tests-passed* 0) (web3-tests/runner::*tests-failed* 0)) (web3-tests/runner::run-{selector}-tests) (let ((total (+ web3-tests/runner::*tests-passed* web3-tests/runner::*tests-failed*))) (format t "~&cl-workbench-checks: ~D~%" total) (when (zerop total) (error "{selector}: no tests ran")) (unless (zerop web3-tests/runner::*tests-failed*) (error "{selector}: ~D test(s) failed" web3-tests/runner::*tests-failed*))))
CL_WORKBENCH_FORM
)

sha256_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    echo "ERROR: sha256sum or shasum is required for runtime identity" >&2
    return 1
  fi
}

CHECKOUT_ID="$(printf '%s' "$ROOT" | sha256_stdin)"
CHECKOUT_SHORT="${CHECKOUT_ID:0:12}"
SESSION_ID="$PROJECT_ID-$CHECKOUT_SHORT"
CONTAINER="${WEB3_LISP_DEV_CONTAINER:-$PROJECT_ID-dev-$CHECKOUT_SHORT}"
FASL_VOLUME="$PROJECT_ID-fasl-dev-$CHECKOUT_SHORT"
PROJECT_LABEL="io.common-lisp-workbench.project"
CHECKOUT_LABEL="io.common-lisp-workbench.checkout"
MANAGED_LABEL="io.common-lisp-workbench.managed"

usage() {
  cat <<USAGE
Usage: scripts/dev.sh COMMAND [ARGS]

Persistent Swank development helper for $PROJECT_ID. The warm image runs
INSIDE the pinned project container ($IMAGE): SBCL never runs on the host.
The container runs scripts/dev-swank-server.lisp as its main process; every
eval is a \`docker exec\` of the Common Lisp Workbench hardened eval client,
so the Swank port is never published to the host. Container, session, and
FASL volume identities are checkout-specific, so two checkouts never collide
or share a writable FASL cache.

Commands:
  start              Start the warm dev container (systems loaded, Swank up)
  stop               Remove the dev container (the FASL volume persists)
  status             Show whether the dev container is running
  doctor             Verify the Docker boundary and required project assets
  identity FIELD     Print checkout-id|session-id|container|image|port|fasl-volume
  eval FORM          Evaluate FORM in the warm image (via cl-workbench)
  test [SELECTOR]    Run the whole suite, or one selector when configured
  test-all           Run the whole suite
  test-form all|one SELECTOR
                     Print the Lisp form the test commands evaluate
  docs-check         Verify documentation transcripts in a cold container
  logs               Show the dev container's output
  help               Show this help

Environment:
  DEV_SWANK_PORT             Swank port INSIDE the container, default 4007
  WEB3_LISP_DEV_CONTAINER
                             Container name, default is checkout-specific; an
                             override is accepted only when its ownership
                             labels match this physical checkout
  DEV_EVAL_TIMEOUT           Eval timeout seconds, default 20 (test: 600,
                             test-all: 3600); on timeout the form is
                             interrupted and the image survives
  DEV_EVAL_MAX_OUTPUT        Output cap in chars, default 10000
Eval exit codes: 0 ok, 1 lisp error, 2 connection error, 3 timed out
(interrupted, image survived), 4 hard hang (restart the image). A long
foreign call cannot be interrupted mid-call and may show rc=4 although the
image recovers when it returns.

Cold verification of record stays with scripts/docker-test.sh (the full
suite in a fresh container).
USAGE
}

# One docker call reads an object's state and ownership labels into
# INSPECT_STATUS / INSPECT_PROJECT / INSPECT_CHECKOUT / INSPECT_MANAGED.
# Absence is the exit status, not the output: a missing object still prints
# an empty line under --format. Fields are `|`-separated, not whitespace,
# because `read` collapses whitespace runs and an empty label would shift
# its neighbours.
inspect_object() { # $1 docker object kind, $2 name, $3 --format template
  local line
  line="$("$DOCKER" "$1" inspect --format "$3" "$2" 2>/dev/null)" || return 1
  IFS='|' read -r INSPECT_STATUS INSPECT_PROJECT INSPECT_CHECKOUT INSPECT_MANAGED <<<"$line"
}

labels_template() { # $1 label-map path inside the template
  printf '{{ index %s "%s" }}|{{ index %s "%s" }}|{{ index %s "%s" }}' \
    "$1" "$PROJECT_LABEL" "$1" "$CHECKOUT_LABEL" "$1" "$MANAGED_LABEL"
}

inspect_container() {
  inspect_object container "$CONTAINER" \
    "{{ .State.Status }}|$(labels_template .Config.Labels)"
}

inspect_volume() { # volumes have no state; the status field stays empty
  inspect_object volume "$FASL_VOLUME" "|$(labels_template .Labels)"
}

# The labels every object we create carries (see the run/create sites); they
# are the guard against touching another checkout's container or volume on
# the shared daemon.
inspected_is_owned() {
  [ "$INSPECT_PROJECT" = "$PROJECT_ID" ] && \
    [ "$INSPECT_CHECKOUT" = "$CHECKOUT_ID" ] && \
    [ "$INSPECT_MANAGED" = "true" ]
}

refuse_foreign_container() {
  echo "ERROR: refusing foreign or unlabeled container: $CONTAINER" >&2
  echo "       expected checkout ownership: $CHECKOUT_ID" >&2
  return 2
}

container_owned() {
  inspect_container && inspected_is_owned
}

require_owned_container() {
  container_owned || refuse_foreign_container
}

container_state() { # prints running|stopped|absent
  inspect_container || {
    echo absent
    return 0
  }
  inspected_is_owned || {
    refuse_foreign_container
    return $?
  }
  case "$INSPECT_STATUS" in
    running) echo running ;;
    *) echo stopped ;;
  esac
}

# `docker image inspect NAME` fails to resolve short names on some
# containerd-store daemons even when the image exists; `image ls -q` resolves
# them correctly, so presence checks must use it.
image_present() {
  [ -n "$("$DOCKER" image ls -q "$IMAGE")" ]
}

ensure_image() {
  if ! image_present; then
    echo "Image $IMAGE not found — building (one-time)..." >&2
    "$DOCKER" build -f "$ROOT/docker/Dockerfile" -t "$IMAGE" "$ROOT"
  fi
}

ensure_volume() {
  if inspect_volume; then
    inspected_is_owned || {
      echo "ERROR: refusing foreign FASL volume: $FASL_VOLUME" >&2
      return 2
    }
  else
    "$DOCKER" volume create \
      --label "$PROJECT_LABEL=$PROJECT_ID" \
      --label "$CHECKOUT_LABEL=$CHECKOUT_ID" \
      --label "$MANAGED_LABEL=true" \
      "$FASL_VOLUME" >/dev/null
  fi
}

# The Workbench REPL descriptor: `cl-workbench repl eval` (and therefore
# `dev.sh eval`) reads it, so it is written by every successful start and
# removed by stop — whichever entry point (dev.sh or the adapter) was used.
DESCRIPTOR="$ROOT/.cl-workbench/state/repl.json"

write_descriptor() {
  local state_dir temporary
  state_dir="$(dirname "$DESCRIPTOR")"
  temporary="$DESCRIPTOR.tmp.$$"
  (umask 077 && mkdir -p "$state_dir")
  umask 077
  printf '%s\n' \
    '{' \
    '  "schema_version": 1,' \
    '  "transport": "swank",' \
    '  "host": "127.0.0.1",' \
    "  \"port\": $PORT," \
    '  "package": "COMMON-LISP-USER",' \
    "  \"session_id\": \"$SESSION_ID\"" \
    '}' >"$temporary"
  mv "$temporary" "$DESCRIPTOR"
}

start_server() {
  local state
  state="$(container_state)" || return $?
  case "$state" in
    running)
      echo "Dev container already running: $CONTAINER"
      write_descriptor
      return 0
      ;;
    stopped)
      echo "Removing exited container $CONTAINER"
      require_owned_container
      "$DOCKER" rm -f "$CONTAINER" >/dev/null
      ;;
  esac
  ensure_image
  ensure_volume
  "$DOCKER" run --detach --init --name "$CONTAINER" \
    --label "$PROJECT_LABEL=$PROJECT_ID" \
    --label "$CHECKOUT_LABEL=$CHECKOUT_ID" \
    --label "$MANAGED_LABEL=true" \
    --volume "$ROOT:/workspace" \
    --volume "$FASL_VOLUME:/fasl-cache" \
    --workdir /workspace \
    --env DEV_SWANK_PORT="$PORT" \
    "$IMAGE" \
    sbcl --dynamic-space-size "$HEAP" --noinform \
      --load scripts/dev-swank-server.lisp >/dev/null

  # Cold FASL volume: the first build can take minutes; cap the wait at 15 min.
  local i state2
  for i in {1..900}; do
    if "$DOCKER" logs "$CONTAINER" 2>&1 | grep -q "Swank dev image ready"; then
      write_descriptor
      echo "Started $PROJECT_ID dev container $CONTAINER (Swank on :$PORT inside)"
      return 0
    fi
    state2="$(container_state)" || return $?
    if [[ "$state2" != running ]]; then
      echo "Dev container exited during startup:" >&2
      "$DOCKER" logs "$CONTAINER" 2>&1 | tail -40 >&2
      return 1
    fi
    sleep 1
  done
  echo "Timed out waiting for Swank in $CONTAINER" >&2
  "$DOCKER" logs "$CONTAINER" 2>&1 | tail -40 >&2
  return 1
}

stop_server() {
  local state
  state="$(container_state)" || return $?
  if [[ "$state" == absent ]]; then
    echo "No dev container is running."
  else
    require_owned_container
    "$DOCKER" rm -f "$CONTAINER" >/dev/null
    echo "Removed dev container $CONTAINER"
  fi
  rm -f "$DESCRIPTOR"
}

status_server() {
  local state
  state="$(container_state)" || return $?
  echo "Dev container $CONTAINER: $state"
  if image_present; then
    echo "Dev image $IMAGE: present"
  else
    echo "Dev image $IMAGE: absent (start builds it)"
  fi
  if inspect_volume; then
    if inspected_is_owned; then
      echo "FASL volume $FASL_VOLUME: present (ownership verified)"
    else
      echo "FASL volume $FASL_VOLUME: PRESENT BUT FOREIGN" >&2
      return 2
    fi
  else
    echo "FASL volume $FASL_VOLUME: absent (start creates it)"
  fi
  echo "Checkout identity: $CHECKOUT_ID"
  if [ "$state" = running ]; then
    local published
    published="$("$DOCKER" port "$CONTAINER")"
    if [ -z "$published" ]; then
      echo "Container boundary: no host ports published"
    else
      echo "ERROR: dev container publishes a host port:" >&2
      echo "$published" >&2
      return 1
    fi
  fi
}

doctor() {
  command -v "$DOCKER" >/dev/null 2>&1 || {
    echo "ERROR: Docker CLI is unavailable; host interpreter fallback is forbidden" >&2
    return 1
  }
  "$DOCKER" version >/dev/null 2>&1 || {
    echo "ERROR: Docker daemon is unavailable; host interpreter fallback is forbidden" >&2
    return 1
  }
  local required
  # ${arr[@]+"${arr[@]}"}: an empty array is "unbound" under set -u in bash 3.2.
  for required in ${REQUIRED_PATHS[@]+"${REQUIRED_PATHS[@]}"}; do
    [ -e "$ROOT/$required" ] || {
      echo "ERROR: required path is missing: $required (see the project instructions)" >&2
      return 1
    }
  done
  [ -f "$ROOT/scripts/dev-swank-server.lisp" ] || {
    echo "ERROR: scripts/dev-swank-server.lisp is missing" >&2
    return 1
  }
  status_server
}

require_running() {
  local state
  state="$(container_state)" || return $?
  if [[ "$state" != running ]]; then
    echo "Dev container $CONTAINER is not running; run: scripts/dev.sh start" >&2
    return 2
  fi
}

identity_field() {
  [ "$#" -eq 1 ] || return 2
  case "$1" in
    checkout-id) printf '%s\n' "$CHECKOUT_ID" ;;
    session-id) printf '%s\n' "$SESSION_ID" ;;
    container) printf '%s\n' "$CONTAINER" ;;
    image) printf '%s\n' "$IMAGE" ;;
    port) printf '%s\n' "$PORT" ;;
    fasl-volume) printf '%s\n' "$FASL_VOLUME" ;;
    *) echo "ERROR: unknown identity field: $1" >&2; return 2 ;;
  esac
}

# Workbench adapter-only path. The canonical client is streamed over stdin;
# it is never copied into this project or persisted in the container.
exec_workbench_eval_client() {
  [ "$#" -ge 2 ] || {
    echo "ERROR: adapter-eval requires CLIENT and FORM" >&2
    return 2
  }
  local client="$1"
  shift
  [ -f "$client" ] || { echo "ERROR: canonical eval client is unavailable" >&2; return 2; }
  require_running || return $?
  local args=(--interactive --workdir /workspace
              --env DEV_SWANK_HOST=127.0.0.1
              --env DEV_SWANK_PORT="$PORT")
  [[ -n "${DEV_EVAL_TIMEOUT:-}" ]] && args+=(--env DEV_EVAL_TIMEOUT="$DEV_EVAL_TIMEOUT")
  [[ -n "${DEV_EVAL_MAX_OUTPUT:-}" ]] && args+=(--env DEV_EVAL_MAX_OUTPUT="$DEV_EVAL_MAX_OUTPUT")
  [[ -n "${DEV_SWANK_PACKAGE:-}" ]] && args+=(--env DEV_SWANK_PACKAGE="$DEV_SWANK_PACKAGE")
  "$DOCKER" exec "${args[@]}" "$CONTAINER" \
    sbcl --script /dev/stdin "$@" <"$client"
}

eval_form() {
  if [[ $# -eq 0 ]]; then
    echo "eval requires a Lisp FORM argument" >&2
    return 2
  fi
  local workbench="${CL_WORKBENCH_BIN:-cl-workbench}"
  if [[ "$workbench" = */* ]]; then
    [ -x "$workbench" ] || {
      echo "ERROR: Common Lisp Workbench CLI is not executable: $workbench" >&2
      return 2
    }
  elif ! command -v "$workbench" >/dev/null 2>&1; then
    echo "ERROR: cl-workbench is unavailable; host Lisp fallback is forbidden" >&2
    return 2
  fi
  "$workbench" repl eval "$@"
}

# The forms are the single source for the warm (eval) and cold
# (docker-test.sh) paths. A selector is restricted to the characters the
# adapter accepts so it can be spliced into a form safely.
test_form() {
  case "${1:-}" in
    all)
      [ "$#" -eq 1 ] || return 2
      printf '%s\n' "$TEST_ALL_FORM"
      ;;
    one)
      [ "$#" -eq 2 ] || return 2
      [ -n "$TEST_ONE_FORM" ] || {
        echo "ERROR: per-selector tests are not configured for $PROJECT_ID; run the whole suite" >&2
        return 2
      }
      case "$2" in
        *[!A-Za-z0-9._:+-]*|'')
          echo "ERROR: unsafe test selector: $2" >&2
          return 2
          ;;
      esac
      printf '%s\n' "${TEST_ONE_FORM//\{selector\}/$2}"
      ;;
    *) return 2 ;;
  esac
}

test_one() {
  if [[ $# -ne 1 ]]; then
    echo "test requires one selector" >&2
    return 2
  fi
  local form
  form="$(test_form one "$1")" || return $?
  DEV_EVAL_TIMEOUT="${DEV_EVAL_TIMEOUT:-600}" \
    DEV_EVAL_MAX_OUTPUT="${DEV_EVAL_MAX_OUTPUT:-2000000}" eval_form "$form"
}

# A chatty runner prints one line per test; the default 10k eval output cap
# would cut off the trailing cl-workbench-checks line.
test_all() {
  DEV_EVAL_TIMEOUT="${DEV_EVAL_TIMEOUT:-3600}" \
    DEV_EVAL_MAX_OUTPUT="${DEV_EVAL_MAX_OUTPUT:-2000000}" eval_form "$TEST_ALL_FORM"
}

docs_check() {
  [ "$DOCS_CONFIGURED" -eq 1 ] || {
    echo "ERROR: docs verification is not configured for $PROJECT_ID" >&2
    return 2
  }
  ensure_image
  exec "$ROOT/scripts/docker-sbcl.sh" --dynamic-space-size "$HEAP" \
    --non-interactive --load scripts/docs-check.lisp
}

show_logs() {
  require_owned_container
  "$DOCKER" logs "$CONTAINER" "$@"
}

cmd="${1:-help}"
shift || true
case "$cmd" in
  start) start_server ;;
  stop) stop_server ;;
  status) status_server ;;
  doctor) doctor ;;
  identity) identity_field "$@" ;;
  adapter-eval) exec_workbench_eval_client "$@" ;;
  eval) eval_form "$@" ;;
  test)
    if [ "$#" -eq 0 ]; then test_all; else test_one "$@"; fi
    ;;
  test-all) test_all ;;
  test-form) test_form "$@" ;;
  docs-check) docs_check ;;
  logs) show_logs "$@" ;;
  help|-h|--help) usage ;;
  *) echo "Unknown command: $cmd" >&2; usage >&2; exit 2 ;;
esac
