#!/usr/bin/env bash
# cl-workbench-template: docker-test.sh.template template=7f9f8a4ec110 rendered=17a84c8db1c1 version=0.13.0-dev
# The cold battery: load the project's systems in a fresh containerized SBCL
# (see docker-sbcl.sh) and run the test form scripts/dev.sh also uses for the
# warm image, so both paths run the same code. Exits non-zero on any failure,
# and the form prints `cl-workbench-checks: N` for the counted gate.
# Generated by `cl-workbench init`; regenerate with `cl-workbench init --update`.
#
# Usage:
#   scripts/docker-test.sh              # full suite
#   scripts/docker-test.sh SELECTOR     # one selector, when the project defines one
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
if [ "$#" -eq 0 ]; then
  FORM="$("$HERE/dev.sh" test-form all)"
else
  FORM="$("$HERE/dev.sh" test-form one "$1")"
fi

exec "$HERE/docker-sbcl.sh" --dynamic-space-size 4096 --non-interactive \
  --eval '(asdf:load-system "web3/tests")' \
  --eval "$FORM"
