#!/usr/bin/env bash
# cl-workbench-template: docker-sbcl.sh.template template=c91c7b65699d rendered=7d4fd1bd42e5 version=0.13.0-dev
# Run the project's containerized SBCL with the repo mounted at /workspace —
# isolates this project's toolchain from any other SBCL on the host. See
# docker/Dockerfile. Generated by `cl-workbench init`; regenerate a stale copy
# with `cl-workbench init --update`.
#
# Usage:
#   scripts/docker-sbcl.sh                          # interactive REPL
#   scripts/docker-sbcl.sh --non-interactive --eval '(+ 1 2)'
#
# The FASL cache lives in a named volume scoped to THIS checkout's path: a
# volume shared by two checkouts is written by both and corrupts silently.
# Override with WEB3_LISP_FASL_VOLUME only if you really want to share one.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
IMAGE=web3-lisp-sbcl:2.5.2-1
REQUIRED_PATHS=()
# Host environment variables forwarded into the container when they are set.
PASSTHROUGH_ENV=("WEB3_INTEGRATION" "WEB3_TEST_RPC_URL")

sha256_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    echo "ERROR: sha256sum or shasum is required for runtime identity" >&2
    exit 1
  fi
}
CHECKOUT_SHORT="$(printf '%s' "$REPO" | sha256_stdin)"
CHECKOUT_SHORT="${CHECKOUT_SHORT:0:12}"
FASL_VOLUME="${WEB3_LISP_FASL_VOLUME:-web3-lisp-fasl-cold-$CHECKOUT_SHORT}"

# ${arr[@]+"${arr[@]}"}: an empty array is "unbound" under set -u in bash 3.2.
for required in ${REQUIRED_PATHS[@]+"${REQUIRED_PATHS[@]}"}; do
  [ -e "$REPO/$required" ] || {
    echo "ERROR: required path is missing: $required (see the project instructions)" >&2
    exit 1
  }
done

# The daemon, before anything that needs it: an unreachable daemon must not
# announce itself as "image not found — building".
if ! docker info >/dev/null 2>&1; then
  echo "ERROR: the Docker daemon is not reachable." >&2
  echo "       Every build, test and eval in this project runs inside the" >&2
  echo "       pinned container; there is no host fallback." >&2
  exit 1
fi

# `docker image inspect NAME` fails to resolve short names on some
# containerd-store daemons even when the image exists; `image ls -q` does.
if [ -z "$(docker image ls -q "$IMAGE")" ]; then
  echo "Image $IMAGE not found — building (one-time)..." >&2
  docker build -f "$REPO/docker/Dockerfile" -t "$IMAGE" "$REPO"
fi

TTY_FLAGS="-i"
[ -t 0 ] && [ -t 1 ] && TTY_FLAGS="-it"

ENV_ARGS=()
for name in ${PASSTHROUGH_ENV[@]+"${PASSTHROUGH_ENV[@]}"}; do
  [ -z "${!name+x}" ] || ENV_ARGS+=(--env "$name")
done

exec docker run --rm $TTY_FLAGS \
  -v "$REPO:/workspace" \
  -v "$FASL_VOLUME":/fasl-cache \
  --label "io.common-lisp-workbench.project=web3-lisp" \
  --label "io.common-lisp-workbench.checkout=$CHECKOUT_SHORT" \
  -w /workspace \
  ${ENV_ARGS[@]+"${ENV_ARGS[@]}"} \
  "$IMAGE" sbcl "$@"
